<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>Sasayaki</AssemblyName>
    <ApplicationIcon>Assets/Sasayaki.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets/Sasayaki.ico" />
    <ProjectReference Include="../Sasayaki.Core/Sasayaki.Core.csproj" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
</Project>
